### ISSUE TITLE
Name length limited

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/land-explorer-front-end#14]
There is a low character cap on the lenght of a marker name in LE. Looks like 18. Can't see a reason for this arbitrariy low cap.

**Comment by lin-d-hop** [comment]
Def higher than 18 now.
I'm guessing the limit is defined by the DB.
![Screenshot from 2022-07-06 11-10-24](https://user-images.githubusercontent.com/8669848/177527211-13cc51d3-d062-4eaa-acb3-04c78723ca98.png)
