### ISSUE TITLE
Support simultaneous editing of maps

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/land-explorer-front-end#16]
Explore what actions are reasonable to support when more than 1 instance of a map is being editied.

Visual clue and inhibiting you from editied an object being edited by someone else
Pushing changes made by others to your view. 
How does that effect undo stack?

**Comment by ColmMassey** [comment]
Was this closed becasue it already works, is too difficult, or needs to become an epic? @lin-d-hop

**Comment by lin-d-hop** [comment]
It is not a well described issue and is not yet a priority. It will be reopened under the Epic 'Collaborative Mapping' with enough detail to be implementable. It is already linked to that epic so is not lost.
