### ISSUE TITLE
SSL Certs using Let'sEncrypt

### ISSUE THREAD

**Issue by lin-d-hop** [SolidarityEconomyAssociation/land-explorer-front-end#50]
Use Let'sEncryot for free and automatically generated SSL certs for Land Explorer.

This needs to be completed by June 6th when previous certs expire.

This task is blocking the migration of all LX servers to the latest backend, which again needs to be complete by June 6th cert expiry date on main LX site.

**Comment by lin-d-hop** [comment]
@King-Mob We now have an active email address for LX: landexplorer@digitalcommons.coop

Can you update the Let'sEncrypt to use this as the main email address?
I'll create other issues for other email aspects of the app but would be good to update this one before closing the SSL Certs issue :pray:

**Comment by King-Mob** [comment]
Not sure how to verify that this worked, but I ran 
`certbot update_account --email landexplorer@digitalcommons.coop`
 and got 
`Your e-mail address was updated to landexplorer@digitalcommons.coop.`
So I think this has happened?
