### ISSUE TITLE
Name User Group data after User Groups

### ISSUE THREAD

**Issue by lin-d-hop** [SolidarityEconomyAssociation/land-explorer-front-end#58]
## Description

The excellent addition of user-specific data to LX is great! This issue is to suggest a few improvements to help the feature be scalable and more flexible.

Currently all data for a user is clustered together as 'Your Data'. it would be great if instead we had a cluster for each data group available to the user and gave the name of the group eg 'Resilient Green Spaces'. This was we can make better use of the data model that allows users to have multiple data groups. 

As the data grows we'll quickly get to the point of an overloaded UX. I think we'll want to create the ability to show and hide individual layers in the future through a sexy UI. But for now let's just have the ability to expand and collapse each data set, including the global 'Land Data'.

![Screenshot from 2022-05-26 12-09-07](https://user-images.githubusercontent.com/8669848/170477820-eb6b65b9-44a3-4607-b280-d11b043c285e.png)

## Acceptance Criteria

- Each data group is grouped together in the UI.
- Data groups are expandable and contractible
- Data Groups are grouped in the UI as groups and labelled according to the Data Group name in the DB

@MelissaMc20 It would be great to have your design eye on this. I know it's a simple little design task. I promise more interesting things on LX soon!

**Comment by King-Mob** [comment]
Can we rename the panel something like Data Layers, then have the Land Data just be the first collapsible group? Also we could probably rename Land Data something like Common Data as well?

**Comment by King-Mob** [comment]
@lin-d-hop @MelissaMc20 I've put a non-designed version of this on the staging, can apply design when I get one

**Comment by lin-d-hop** [comment]
All looks good to me as a first improvement. Let's come back to this after our design sweep :)
