### ISSUE TITLE
Create new static site

### ISSUE THREAD

**Issue by lin-d-hop** [SolidarityEconomyAssociation/land-explorer-front-end#69]
## Description

The LX WP site is expensive to host and difficult to maintain as it has a custom theme that can't be updated automatically. Time to move on.

The new static site should basically be a copy of the old to begin with, with any relevant text updates to reflect the shift to Digital Commons.

## Acceptance Criteria

- New site renders well on all devices eg mobile, tablet etc
- Content unchanged, or as few changes as possible
- URLs - let's bring some consistency. It would be great if:
landexplorer.coop and landexplorer.cc both point to the static site. .coop is the main site and .cc is a redirect.
Within the menu a link to app.landexplorer.coop directs to the app

**Comment by King-Mob** [comment]
@lin-d-hop created a repo for the static site here: https://github.com/SolidarityEconomyAssociation/land-explorer-static

**Comment by lin-d-hop** [comment]
I've added the static site repo to this workspace so we can track issues across all LX projects here.

**Comment by lin-d-hop** [comment]
Small issue on one of the images:

https://user-images.githubusercontent.com/8669848/181745001-21b138cc-e99d-4140-9c9f-18ba5dbd49a6.mp4

**Comment by lin-d-hop** [comment]
Do we still want to say 'site by Edot3' in the footer?
![Screenshot from 2022-07-29 11-57-16](https://user-images.githubusercontent.com/8669848/181745298-558f33c6-4902-4ec5-b983-5ccb3c1d74cf.png)

**Comment by lin-d-hop** [comment]
Back to In Dev for the image issue.
If you think that the site was still by Edot3 @King-Mob then let's keep that for now. Otherwise, let's remove.

**Comment by King-Mob** [comment]
yes, can see the issue

**Comment by King-Mob** [comment]
resolved on staging
