### ISSUE TITLE
Update LX Email address

### ISSUE THREAD

**Issue by lin-d-hop** [SolidarityEconomyAssociation/land-explorer-front-end#74]
## Description
Previously LX had two email addresses:
hello@landexplorer.cc
admin@landexplorer.cc

These are being replaced with:
landexplorer@digitalcommons.coop

## Acceptance Criteria
- COnfigure emails to send FROM landexplorer@digitalcommons.coop throughout the app
- Build a list of anywhere within the LX codebase or server configuration in which an email address has been provided. It would be useful to document this. Maybe there is nothing other than Let'sEncrypt.... but it would be helpful to have a think and confirm.
- Update these email addresses to the new email address.

**Comment by King-Mob** [comment]
closed here: https://github.com/SolidarityEconomyAssociation/land-explorer-back-end/pull/5
