### ISSUE TITLE
Resetting Password fails

### ISSUE THREAD

**Issue by lin-d-hop** [SolidarityEconomyAssociation/land-explorer-front-end#84]
**Describe the bug**
On pressing reset password the button 
**To Reproduce**
1. ON login screen hit 'Forgot Password'
2. Enter email and press Reset
3. Nothing happens

**Expected behaviour**
I expect to know that the button press was received, and then receive an email

**Screenshots/GIFs**

https://user-images.githubusercontent.com/8669848/179366477-727df9b8-a8a4-42dc-ad4a-651ec5f24a57.mp4

**Context (please complete the following information):**
 - Device: [e.g. iPhone6] PC
 - OS: [e.g. iOS8.1] Ubuntu
 - Browser [e.g. stock browser, safari] CHrome
 - Version [e.g. 22] 2.0

**Additional context**
This worked before the hotfix so probably related to the last release.
Could we have prevented this with unit tests?

**Comment by ColmMassey** [comment]
I observe the same on  Windows 10 PC using latest Firefox.

**Comment by King-Mob** [comment]
I observe it on landexplorer.coop but not on testing-lx.com

So, something on prod but not staging? That's quite confusing

**Comment by ColmMassey** [comment]
I can now get as far as having a new password sent to my email account. However the sendgrid link presented in the email

takes me to 

https://app.landexplorer.cc/auth/

which is the old address.

If I ignore it and manually go to new login page, the new password works. :-)

**Comment by King-Mob** [comment]
added that as #86
