### ISSUE TITLE
use a better process manager for the backend

### ISSUE THREAD

**Issue by King-Mob** [SolidarityEconomyAssociation/land-explorer-front-end#85]

**Comment by King-Mob** [comment]
#84 was caused by the very simplistic process manager I chose for the backend failing. I don't think we can continue to use this, so I am looking at using pm2, a popular process manager with exciting things we can use like logs and clusters

**Comment by King-Mob** [comment]
What has changed:
- to deploy the backend we just cd into the land-explorer-backend directory and run `npm run build`
- pm2 notices the transpiled js files have changed, and restarts itself

To verify, ssh into the staging or production server and run `pm2 monit` and you can see a nice monitor screen for our app with live logs showing up if you interact with the backend at the same time

**Comment by lin-d-hop** [comment]
Nice updates :)
Assuming I can close this now :)
