### ISSUE TITLE
Registration on small screens needs scroll

### ISSUE THREAD

**Issue by lin-d-hop** [SolidarityEconomyAssociation/land-explorer-front-end#87]
**Describe the bug**
On small screens the registration process does not work as the 'register' button and 'cancel' button cannot be seen. There is no way to scroll to this.

I think scroll is the solution, rather than a responsively sized box. video below of playing with screen sizes to see how the page renders.

**To Reproduce**
1. On a screen of height less than 850 go to [registration](https://landexplorer.coop/auth/register)
2. Enter all the details 
3. Be stuck

**Expected behaviour**
Clear ability to nagivate to the buttons using scroll

**Screenshots/GIFs**
[Kate's experience here.
](https://www.loom.com/share/f0e49d2cdab541589c113dcb6f81f661)

**Context

https://user-images.githubusercontent.com/8669848/179987101-ff2be1ad-dd3b-4ae4-81f1-2bb879828def.mp4

 (please complete the following information):**
 - Device: Kate was on a 13" mac
 - OS: 
 - Browser - chrome tested
 - Version: 2.0

**Additional context**

**Comment by King-Mob** [comment]
Not perfect on mobile but that's more of a width issue and not sure we're currently supporting mobile UX

**Comment by lin-d-hop** [comment]
Tested and we have a nice functioning scroll now. Great work!
