### ISSUE TITLE
More issues with SSL and access issues

### ISSUE THREAD

**Issue by lin-d-hop** [SolidarityEconomyAssociation/land-explorer-front-end#98]
landexplorer.cc curr
![Screenshot from 2022-08-30 16-14-00](https://user-images.githubusercontent.com/8669848/187474918-64542741-d132-461d-9db2-e9b4a946000b.png)
ently is showing an invalid certificate. Sometimes it redirects to LX.coop but not always.

landexplorer.coop is also showing an insecure site.
![Screenshot from 2022-08-30 16-14-09](https://user-images.githubusercontent.com/8669848/187474900-17c83b03-01bd-49e7-b4e8-22eff6fb4d4b.png)

We've just sent a mass email out to old users so, to be honest, this just looks really bad.

Can you replicate yet, John? Seems you are the only person who has never experienced this, which might be a clue.

**Comment by King-Mob** [comment]
I think I fixed it
